name: Alerta no Teams

on:
  push:
    branches:
      - main

jobs:
  alerta:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar alerta
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
                "text": "Novo commit!\nRepo: ${{ github.repository }}\nAutor: ${{ github.actor }}\nBranch: ${{ github.ref_name }}"
              }' \
          "${{ secrets.TEAMS_WEBHOOK }}"