name: Testes Unitários

on:
  pull_request:
    branches:
      - main

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependências
        run: pip install pytest

      - name: Rodar testes
        run: pytest teste_calculadora.py -v
